version: '3'

services:
  db:
    image: mysql:5.7.13
    ports:
      - "4406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - $PWD/init/:/docker-entrypoint-initdb.d
    networks:
      - si
  admin:
    image: phpmyadmin/phpmyadmin
    networks:
      - si
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8888:80"
    links:
      - "db:db"
    depends_on:
      - db
  korisnici:
    image: si/korisnici
    environment:
      - DB_URL=jdbc:mysql://db:3306/si?useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - si
    links:
      - "db:db"
    ports:
      - "9090:8080"
    depends_on:
      - db





networks:
  si: